export const products = [
  {
    id: 1,
    name: "FIZZA",
    rating: "5",
    title: "UNLIMITED CHICKEN FRY",
    price: 23,
    image: "images/chicken-wings.png",
  },
  {
    id: 2,
    name: "CHICKEN",
    rating: "4",
    title: "BANGLADESHI SENDRUES",
    price: 53,
    image: "images/wings.png",
  },
  {
    id: 3,
    name: "FULL BURGAR",
    rating: "3",
    title: "DOUBLE STUCK BURGER",
    price: 33,
    image: "images/zdjecie1.png",
  },
  {
    id: 4,
    name: "FULL BURGAR",
    rating: "3",
    title: "DOUBLE STUCK BURGER",
    price: 33,
    image: "images/zdjecie1.png",
  },
  {
    id: 5,
    name: "FULL BURGAR",
    rating: "5",
    title: "CHINIS POPULAR NOUDLUS",
    price: 13,
    image: "images/noodles.png",
  },
  {
    id: 6,
    name: "CHICKEN",
    rating: "2",
    title: "UNLIMITED FULL CHICKEN",
    price: 66,
    image: "images/chicken.png",
  },
  {
    id: 7,
    name: "KEBAB",
    rating: "5",
    title: "AMAZING KEBABOS",
    price: 53,
    image: "images/tortilla.png",
  },
];
