export const products = [
  {
    id: 1,
    name: "FIZZA",
    rating: "5",
    title: "UNLIMITED CHICKEN FRY",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 23,
    image: "images/chicken-wings.png",
    numReviews: 3,
  },
  {
    id: 2,
    name: "CHICKEN",
    rating: "4",
    title: "BANGLADESHI SENDRUES",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 53,
    image: "images/wings.png",
    numReviews: 6,
  },
  {
    id: 3,
    name: "FULL BURGAR",
    rating: "4.5",
    title: "DOUBLE STUCK BURGER",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 33,
    image: "images/zdjecie1.png",
    numReviews: 9,
  },
  {
    id: 4,
    name: "FULL BURGAR",
    rating: "3",
    title: "DOUBLE STUCK BURGER",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 33,
    image: "images/zdjecie1.png",
    numReviews: 5,
  },
  {
    id: 5,
    name: "FULL BURGAR",
    rating: "5",
    title: "CHINIS POPULAR NOUDLUS",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 13,
    image: "images/noodles.png",
    numReviews: 13,
  },
  {
    id: 6,
    name: "CHICKEN",
    rating: "3.5",
    title: "UNLIMITED FULL CHICKEN",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 66,
    image: "images/chicken.png",
    numReviews: 8,
  },
  {
    id: 7,
    name: "KEBAB",
    rating: "5",
    title: "AMAZING KEBABOS",
    description: "Est do excepteur sunt eu et eu cillum ipsum excepteur.",
    price: 53,
    image: "images/tortilla.png",
    numReviews: 11,
  },
];
